language: python
python: 3.7
script:
 - pip install pip -U
 - sh build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output/
  target_branch: master
  on:
    branch: sources
